/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package logingui;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class frmPapa extends javax.swing.JFrame {
frmPacientes p;
frmDoctors d;
    /**
     * Creates new form frmPapa
     */
    public frmPapa() {
        initComponents();
        this.setExtendedState(frmPapa.MAXIMIZED_BOTH);
        this.setTitle("SONRIE: Programa Odontólogico");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuPacientes = new javax.swing.JMenuItem();
        mnuDoctors = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        fileMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Music\\menu.png")); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Menú");

        mnuPacientes.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        mnuPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pain.png"))); // NOI18N
        mnuPacientes.setMnemonic('o');
        mnuPacientes.setText("Pacientes");
        mnuPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPacientesActionPerformed(evt);
            }
        });
        fileMenu.add(mnuPacientes);

        mnuDoctors.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        mnuDoctors.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Music\\medical-team.png")); // NOI18N
        mnuDoctors.setMnemonic('s');
        mnuDoctors.setText("Doctores");
        mnuDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDoctorsActionPerformed(evt);
            }
        });
        fileMenu.add(mnuDoctors);

        mnuSalir.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        mnuSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Music\\exit.png")); // NOI18N
        mnuSalir.setMnemonic('x');
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        fileMenu.add(mnuSalir);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPacientesActionPerformed
        if(!(p instanceof frmPacientes)){//si no hay instancias en memoria
        p=new frmPacientes();//creamos la instancia
        }
        CentrarHijas(p);//centramos la ventana hija en el MDI
        
    }//GEN-LAST:event_mnuPacientesActionPerformed

    private void mnuDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDoctorsActionPerformed
        // TODO add your handling code here:
        if(!(d instanceof frmDoctors)){//si no hay instancias en memoria
        d=new frmDoctors();//creamos la instancia
        }
        CentrarHijas(d);//centramos la ventana hija en el MDI
    }//GEN-LAST:event_mnuDoctorsActionPerformed
    
    void CentrarHijas(JInternalFrame hija){
        int ancho = (panel.getWidth()/2)- hija.getWidth()/2;
        int alto = (panel.getHeight()/2)- hija.getHeight()/2;
        if(hija.isShowing()){//si se está mostrando la ventana hija
            hija.setLocation(ancho, alto);//la centramos
        }else {
            panel.add(hija);
            hija.setLocation(ancho, alto);
            hija.show();//la mostramos
        
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuDoctors;
    private javax.swing.JMenuItem mnuPacientes;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JDesktopPane panel;
    // End of variables declaration//GEN-END:variables

    
}
